config/routes.rb
Rails.application.routes.draw do
  resources :messages, only: [:show, :edit, :create, :update, :index, :destroy] do
    get "reply" => "messages#reply"
    post "create_reply" => "messages#create_reply"
  end

  get "search", as: :meals_search, controller: :meals

  resources :meals do
    resources :messages, only: [:new]
    get :flag
  end
  get "/pages/*id" => 'pages#show', as: :page, format: false

  resource :dashboard, only: :show

  devise_for :users, controllers: {sessions: 'users/sessions', registrations: 'users/registrations'} do

  end
  get ":slug" => 'profiles#show', as: :profiles

  namespace :api, defaults: {format: 'json'} do
    namespace :v1 do
      resources :meals do
        get :flag
      end
      resources :search
      resources :sessions, only: [:create]
      resources :messages
      resources :streams
      devise_for :users, controllers: {registrations: 'api/v1/registrations'}
    end

  end

  root to: "dashboards#home_page_redirecter"
end

app/models/message.rb
class Message < ActiveRecord::Base
  extend ActsAsTree::TreeWalker
  extend ActsAsTree::TreeView
  belongs_to :user
  acts_as_tree order: "id"
 

  def author
    user.full_name
  end 

  def send_message_notification
    MessageNotificationMailer.send_notification(recipient, self).deliver_now
  end

  def recipient
    User.find (self.recipient_id)
  end

  def parentMessage
    if !self.parent_id.nil?
      Message.find (self.parent_id)
    end
  end

  def as_json(options={})
    super(
      :methods => [:author]
    )
  end
end

app/controllers/api/v1/messages_controller.rb
class Api::V1::MessagesController < ApplicationController
  before_action :authenticate_by_token
  include HTTParty
  respond_to :json

  # Create new file to storage log of pushes.
  @push_logger = ::Logger.new(Rails.root.join('log', 'push.log'))

  # Every request needs to inform the APP ID.
  HEADERS = { "Authorization" => ENV['ONESIGNAL_AUTH'], "Content-Type" => "application/json" }

  @body =  {
    "app_id" => '66e1b37a-7fb4-4da5-a4e7-432a296a240d'
  }

  def index
    limit = params[:limit] || 10
    messages = Message.where(recipient_id: @current_user.id).order( 'created_at DESC' )
    render json: messages, status: 200
  end

  def show
    message = Message.where(id: params[:id], recipient_id: @current_user.id).first
    if message
      render json: message, status: 200
    else 
      render json: {status: "404", error: "record not found"}, status: 404
    end
  end   

  def create        
    json = params[:body]
      .permit(:subject, :body, :recipient_id, :parent_id, :user_id)
      .with_defaults(parent_id: 0, subject: '', user_id: @current_user.id)
    message = @current_user.messages.build(json)
    puts message
    if message.save
      push_body = { 
        "app_id" => '66e1b37a-7fb4-4da5-a4e7-432a296a240d',
        "include_external_user_ids" => [json['recipient_id'].to_s],
        "data" => { "type": "new_message" },
        "headings" => { "en" => 'From: ' + @current_user.full_name() },
        "contents" => { "en" => json['body']}
      }.to_json
      HTTParty.post "https://onesignal.com/api/v1/notifications", headers: HEADERS, body: push_body, :debug_output => $stdout
      render json: message, status: 200
    else
      render json: {status: "500", error: "record could not be created at this time"}, status: 500
    end
  end

  def destroy
    message = Message.where(id: params[:id]).first
    if message
      message.delete
      render json: {status: "200", message: "record successfully deleted"}, status: 200
    else 
      render json: {status: "404", error: "record not found"}, status: 404
    end
  end

  def update
    message = Message.where(id: params[:id],user: @current_user).first
    json = params[:body].permit(:subject, :body, :recipient_id)
    if message
      message.update(json)
      render json: message, status: 200
    else
      render json: {status: "404", error: "record not found"}, status: 404
  end

end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_message, only: [:show, :edit, :update, :destroy]
  
  # GET /messages
  # GET /messages.json
  def index
    @sent_messages = current_user.messages
    @recieved_messages = Message.where(recipient_id: current_user.id)
  end

  # GET /messages/1
  # GET /messages/1.json
  def show
  end

  # GET /messages/new
  def new
    @message = current_user.messages.build
    @meal = Meal.find (params[:meal_id])
  end

  # GET /messages/1/edit
  def edit
  end

  # POST /messages
  # POST /messages.json
  def create
    @message = current_user.messages.build(message_params)
      if @message.save
        @message.send_message_notification
       redirect_to @message, notice: 'Message Sent!'       
    end
  end

  def create_reply
    @message = Message.find(params[:message_id])
    @reply = @message.children.build(message_params)
    @reply.recipient_id = @message.user_id
    @reply.user = current_user
    if @reply.save
      redirect_to @message, notice: "Reply Sent!"
    end

  end

  def reply 
    @message = Message.find(params[:message_id])
    @reply = @message.children.build
  end


  # PATCH/PUT /messages/1
  # PATCH/PUT /messages/1.json
  def update
    respond_to do |format|
      if @message.update(message_params)
        format.html { redirect_to @message, notice: 'Message was successfully updated.' }
        format.json { render :show, status: :ok, location: @message }
      else
        format.html { render :edit }
        format.json { render json: @message.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /messages/1
  # DELETE /messages/1.json
  def destroy
    @message.destroy
    respond_to do |format|
      format.html { redirect_to messages_url, notice: 'Message was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_message
      @message = Message.where("id= ? AND (user_id = ? OR recipient_id = ?)",params[:id], current_user.id, current_user.id).first
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def message_params
      params.require(:message).permit(:subject, :body, :user_id, :recipient_id)
    end
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/views/messages/_form.html.erb
<%= form_for(@message) do |f| %>
  <% if @message.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@message.errors.count, "error") %> prohibited this message from being saved:</h2>

      <ul>
      <% @message.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :subject %><br>
    <%= f.text_field :subject, class: "form-control" %>
  </div>
  <div class="field">
    <%= f.label :body %><br>
    <%= f.text_area :body, class: "form-control" %>
  </div>
  <% if @message.new_record? %>

  <div class="field">
    <%= f.hidden_field :recipient_id, value: @meal.user.id %>
    <p>recipient: <%= @meal.user.full_name %></p>
  </div>
  <% end %>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/messages/edit.html.erb
<h1>Editing Message</h1>

<%= render 'form' %>

<%= link_to 'Show', @message %> |
<%= link_to 'Back', messages_path %>

app/views/messages/index.html.erb
<p id="notice"><%= notice %></p>

<h1> Messages</h1>
<h2>Sent Messages</h2>

<table>
  <thead>
    <tr>
      <th>Subject</th>
      <th>Body</th>
      <th>Sent to</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @sent_messages.each do |message| %>
      <tr>
        <td><%= message.subject %></td>
        <td><%= message.body %></td>
        <td><%= message.recipient.full_name %></td>
        <td><%= link_to 'Show', message %></td>
        <td><%= link_to 'Edit', edit_message_path(message) %></td>
        <td><%= link_to 'Destroy', message, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<h2> Recieved Messages</h2>

<table>
  <thead>
    <tr>
      <th>Subject</th>
      <th>Body</th>
      <th>From</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @recieved_messages.each do |message| %>
      <tr>
        <td><%= message.subject %></td>
        <td><%= message.body %></td>
        <td><%= message.user.full_name %></td>
        <td><%= link_to 'Show', message %></td>
        <td><%= link_to 'Edit', edit_message_path(message) %></td>
        <td><%= link_to 'Destroy', message, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/messages/new.html.erb
<h2>New Message</h2>

<%= render 'form' %>

<%= link_to 'Back', messages_path %>

app/views/messages/reply.html.erb
<p>reply to <%= @message.user.full_name %> </p>
<%= form_for(@reply, url: message_create_reply_path(@message)) do |f| %>
  <% if @reply.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@reply.errors.count, "error") %> prohibited this message from being saved:</h2>

      <ul>
      <% @reply.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :subject %><br>
    <%= f.text_field :subject, class: "form-control" %>
  </div>
  <div class="field">
    <%= f.label :body %><br>
    <%= f.text_area :body, class: "form-control" %>
  </div>
  
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/messages/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Subject:</strong>
  <%= @message.subject %>
</p>

<p>
  <strong>Body:</strong>
  <%= @message.body %>
</p>

<p>
  <strong>User:</strong>
  <%= @message.user.full_name %>
</p>

<p>
  <strong>Recipient:</strong>
  <%= @message.recipient.full_name %>
</p>

<%= link_to 'Edit', edit_message_path(@message) %> |
<%= link_to 'Back', messages_path %>|
<%= link_to 'Reply', message_reply_path(@message) %> 

<% @message.children.each do |message| %>
<hr>
<p>
  <strong>Subject:</strong>
  <%= message.subject %>
</p>

<p>
  <strong>Body:</strong>
  <%= message.body %>
</p>

<p>
  <strong>User:</strong>
  <%= message.user.full_name %>
</p>

<p>
  <strong>Recipient:</strong>
  <%= message.recipient.full_name %>
</p>
<%= link_to 'Reply', message_reply_path(@message) %> 
<hr>
<% end %>