config/routes.rb
Rails.application.routes.draw do
  resources :messages, only: [:show, :edit, :create, :update, :index, :destroy] do
    get "reply" => "messages#reply"
    post "create_reply" => "messages#create_reply"
  end

  get "search", as: :meals_search, controller: :meals

  resources :meals do
    resources :messages, only: [:new]
    get :flag
  end
  get "/pages/*id" => 'pages#show', as: :page, format: false

  resource :dashboard, only: :show

  devise_for :users, controllers: {sessions: 'users/sessions', registrations: 'users/registrations'} do

  end
  get ":slug" => 'profiles#show', as: :profiles

  namespace :api, defaults: {format: 'json'} do
    namespace :v1 do
      resources :meals do
        get :flag
      end
      resources :search
      resources :sessions, only: [:create]
      resources :messages
      resources :streams
      devise_for :users, controllers: {registrations: 'api/v1/registrations'}
    end

  end

  root to: "dashboards#home_page_redirecter"
end

app/models/meal.rb
class Meal < ActiveRecord::Base
  belongs_to :user
  scope :personal_meals, -> (user) { where(user_id: user.id) }
  scope :public_meals, -> (user) { ready_to_eat }
  scope :ready_to_eat, -> { where(expires_at: DateTime.now..1.hour.from_now, flagged_for_review: nil)}
  scope :search, -> (name) { where("lower(name) like?", "%#{name.downcase}%")}
  has_attached_file :image, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\Z/

  attr_accessor :ip_address

  geocoded_by :ip_address
  after_validation :geocode

  def author
    user.full_name
  end 

  def image_url_thumb
    image.url(:thumb)
  end	

  def image_url_medium
    image.url(:medium)
  end

  def image_url_orig
    image.url(:original)
  end

  def flagged?
    flagged_for_review?
  end

  def flag!
    self.flagged_for_review = true
    self.save!
  end

  def as_json(options={})
    super(
      :methods => [:image_url_thumb,:image_url_medium,:image_url_orig,:author]
    )
  end

end

app/controllers/api/v1/meals_controller.rb
class Api::V1::MealsController < ApplicationController
  before_action :authenticate_by_token

  respond_to :json

  def index
    limit = params[:limit] || 10
    if params[:my_meals]
      meals = Meal.personal_meals(@current_user)
    else
      meals = Meal.public_meals(@current_user)
    end
    render json: meals, status: 200
  end

  def show
    meal = Meal.find(params[:id])
    if meal
      render json: meal, status: 200
    else 
      render json: {status: "404", error: "record not found"}, status: 404
    end
  end   

  def flag
    meal = Meal.find(params[:meal_id])
    if meal
      meal.flag!
      render json: meal, status: 200
    else 
      render json: {status: "404", error: "record not found"}, status: 404
    end
  end   

  def create        
    json = params.permit(:name, :description, :latitude, :longitude, :image)
    meal = @current_user.meals.build(json)
    meal.expires_at = DateTime.now + 1.hour

    if meal.save
      render json: meal, status: 200
    else
      render json: {status: "500", error: "record could not be created at this time"}, status: 500
    end
  end

  def destroy
   meal = Meal.find(params[:id])
   if meal
    meal.delete
    render json: {status: "200", message: "record successfully deleted"}, status: 200
  else 
    render json: {status: "404", error: "record not found"}, status: 404
  end
  end

  def update
    meal = Meal.find(params[:id])
    json = params.permit(:name, :description, :latitude, :longitude, :image)
    if meal
      meal.update(json)
      render json: meal, status: 200
    else
      render json: {status: "404", error: "record not found"}, status: 404
  end
end
end

app/controllers/meals_controller.rb
class MealsController < ApplicationController
  before_action :authenticate_user!, except: [:show]
  before_action :set_meal, only: [:edit, :update, :destroy]

  # GET /meals
  # GET /meals.json
  def index
    @meals = current_user.meals.all
  end

  # GET /meals/1
  # GET /meals/1.json
  def show
    @meal = Meal.find(params[:id])
  end

  # GET /meals/new
  def new
    @meal = current_user.meals.build
  end

  # GET /meals/1/edit
  def edit
  end

  # POST /meals
  # POST /meals.json
  def create
    @meal = current_user.meals.build(meal_params)
    @meal.ip_address = request.location.ip
    @meal.expires_at = DateTime.now + 1.hour

    respond_to do |format|
      if @meal.save
        format.html { redirect_to @meal, notice: 'Meal was successfully created.' }
        format.json { render :show, status: :created, location: @meal }
      else
        format.html { render :new }
        format.json { render json: @meal.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /meals/1
  # PATCH/PUT /meals/1.json
  def update
    if params[:meal][:expires_at] == "1"
      params[:meal][:expires_at] = 1.hour.from_now
    else 
      params[:meal].delete(:expires_at)
    end

    respond_to do |format|
      if @meal.update(meal_params)
        format.html { redirect_to @meal, notice: 'Meal was successfully updated.' }
        format.json { render :show, status: :ok, location: @meal }
      else
        format.html { render :edit }
        format.json { render json: @meal.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /meals/1
  # DELETE /meals/1.json
  def destroy
    @meal.destroy
    respond_to do |format|
      format.html { redirect_to meals_url, notice: 'Meal was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def search
    @search = Meal.search(params[:q])
    #.near(request.location.coordinates, 20, :order => "distance")
  end

  def flag
   meal = Meal.find(params[:meal_id])
   if meal
     meal.flag!
   end
   redirect_to request.referer, notice: "Meal was flagged for review"
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_meal
    @meal = current_user.meals.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def meal_params
    params.require(:meal).permit(:name, :description, :location, :image, :expires_at)
  end

end

app/helpers/meals_helper.rb
module MealsHelper
  def distance_to_meal(current_location, meal)
    distance = Geocoder::Calculations.distance_between([meal.latitude, meal.longitude], [current_location.latitude,current_location.longitude])
    if distance.to_s == "NaN"
      "No Location"
    else
      "Distance: #{distance}"
    end
  end
end

app/views/meals/_form.html.erb
<%= form_for(@meal, html: { multipart: true } ) do |f| %>
  <% if @meal.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@meal.errors.count, "error") %> prohibited this meal from being saved:</h2>

      <ul>
      <% @meal.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name, class: "form-control" %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description, class: "form-control" %>
  </div>
  <div class="field">
    <%= f.label :location %><br><h6> zip code </h6>
    <%= f.text_field :location, class: "form-control" %>
  </div>

  <div class="field">
    <%= f.label :image %><br>
    <%= f.file_field :image, class: "form-control" %>
  </div>
  <% if !@meal.new_record? %>

<div class="field">
  <%= f.label :expires_at, "republish" %><br>
  <%= f.check_box :expires_at %>
</div>
<% end %>

  <div class="actions">
    <%= f.submit %>
  </div>

<% end %>

app/views/meals/_meal.html.erb
<div class="container" >

  <div id="Meals" class="row list-group">
    <div class="item  col-xs-4 col-md-3">
      <div class="thumbnail">
        <img class="group list-group-image">
        <%= link_to image_tag(meal.image.url(:medium),height: 400, width: 250), meal_path(meal) %>
  <div class="caption">
    <%= link_to meal.name, meal_path(meal) %>
    <p class="group inner list-group-item-text">
    </p>
    <% if meal.flagged? %>
      <span class="label label-default">Flagged For Review</span>
    <% end %>
    <div class="row">
      <div class="col-xs-12 col-md-6">
        <p class="lead">
        <%= meal.description %> </p>
      </div>
      <div class="col-xs-12 col-md-6">
        <%= link_to "Message", new_meal_message_path(meal), class: "btn btn-success" %>
        <%= link_to "Flag", meal_flag_path(meal)  %>
      </div>

      <br clear="all"/>
      <span class="pull-right"><%= distance_to_meal(request.location, meal) %></span>
    </div>
  </div>
      </div>
    </div>    
  </div> 
</div>

app/views/meals/edit.html.erb
<h1>Editing Meal</h1>

<%= render 'form' %>

<%= link_to 'Show', @meal %> |
<%= link_to 'Back', meals_path %>

app/views/meals/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Meals</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th>Location</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @meals.each do |meal| %>
      <tr>
        <td><%= meal.name %></td>
        <td><%= meal.description %></td>
        <td><%= meal.location %></td>      
        <td><%= link_to 'Show', meal %></td>
        <td><%= link_to 'Edit', edit_meal_path(meal) %></td>
        <td><%= link_to 'Destroy', meal, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Meal', new_meal_path %>

app/views/meals/new.html.erb
<h1>New Meal</h1>

<%= render 'form' %>

<%= link_to 'Back', meals_path %>

app/views/meals/search.html.erb
<h1>search</h1>
<div class = "meals">
 <%= render partial: "meals/meal", collection: @search, as: :meal %>
</div>

app/views/meals/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @meal.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @meal.description %>
</p>

<p>
  <strong>Location:</strong>
  <%= @meal.location %>
</p>

<p>
  <strong>Image:</strong>
  <%= image_tag @meal.image.url(:thumb) %>
</p>
<%= link_to 'Edit', edit_meal_path(@meal) %> |
<%= link_to 'Back', meals_path %> |
<%= link_to 'Message', new_meal_message_path(@meal) %>