config/routes.rb
Rails.application.routes.draw do
  resources :messages, only: [:show, :edit, :create, :update, :index, :destroy] do
    get "reply" => "messages#reply"
    post "create_reply" => "messages#create_reply"
  end

  get "search", as: :meals_search, controller: :meals

  resources :meals do
    resources :messages, only: [:new]
    get :flag
  end
  get "/pages/*id" => 'pages#show', as: :page, format: false

  resource :dashboard, only: :show

  devise_for :users, controllers: {sessions: 'users/sessions', registrations: 'users/registrations'} do

  end
  get ":slug" => 'profiles#show', as: :profiles

  namespace :api, defaults: {format: 'json'} do
    namespace :v1 do
      resources :meals do
        get :flag
      end
      resources :search
      resources :sessions, only: [:create]
      resources :messages
      resources :streams
      devise_for :users, controllers: {registrations: 'api/v1/registrations'}
    end

  end

  root to: "dashboards#home_page_redirecter"
end

app/views/layouts/_header.html.erb
<nav class="navbar navbar-static-top navbar-inverse" role="navigation">
  <div class="container">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "Dinewire", dashboard_path, class: "navbar-brand" %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse navbar-ex1-collapse">
      <ul class="nav navbar-nav navbar-right">
        <li></li>
        <li></li>
        <% if user_signed_in? %>
          <li>
            <%= link_to new_meal_path do %>
              <span class="glyphicon glyphicon-cutlery"></span> Add Meal
            <% end %>
          </li>
          <li><%= link_to "Messages", messages_path %></li>
          <li><%= link_to "My Profile", profiles_path(slug: current_user.user_name) %></li>
          <li><%= link_to "Account Settings", edit_user_registration_path %></li>
          <li><%= link_to "Log out", destroy_user_session_path, method: :delete %></li>
        <% else %>
          <li><%= link_to "Sign in", new_user_session_path %></li>
        <% end %>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Food on demand</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
</head>
<% unless @disable_navbar -%>
  <%= render 'layouts/header' %>
<% end %>
 <%= yield %>


</body>
</html>

app/views/layouts/landing_page.html.erb
<!DOCTYPE html>
<html lang="en" class=" js video audio"><head><link type="text/css" rel="stylesheet" href="http://fonts.googleapis.com/css?family=Roboto:300,400,500,700"><style type="text/css">.gm-style .gm-style-cc span,.gm-style .gm-style-cc a,.gm-style .gm-style-mtc div{font-size:10px}</style><style type="text/css">@media print {  .gm-style .gmnoprint, .gmnoprint {    display:none  }}@media screen {  .gm-style .gmnoscreen, .gmnoscreen {    display:none  }}</style><style type="text/css">.gm-style{font-family:Roboto,Arial,sans-serif;font-size:11px;font-weight:400;text-decoration:none}.gm-style img{max-width:none}</style>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">
  <!--title-->
    <title>Dinewire| HTML Landing Template</title>
  
  <!--Google Fonts-->
  <link href="http://fonts.googleapis.com/css?family=Raleway:400,300,500,700,800,100,600" rel="stylesheet" type="text/css">
  <link href="http://fonts.googleapis.com/css?family=Roboto:400,900" rel="stylesheet" type="text/css">
  <link href="http://fonts.googleapis.com/css?family=Pacifico" rel="stylesheet" type="text/css">
  
    <!--[if lt IE 9]>
      <script src="js/html5shiv.js"></script>
      <script src="js/respond.min.js"></script>
    <![endif]-->       
    <link rel="shortcut icon" href="images/ico/favicon.ico">
    <link rel="apple-touch-icon-precomposed" sizes="144x144" href="images/ico/apple-touch-icon-144-precomposed.png">
    <link rel="apple-touch-icon-precomposed" sizes="114x114" href="images/ico/apple-touch-icon-114-precomposed.png">
    <link rel="apple-touch-icon-precomposed" sizes="72x72" href="images/ico/apple-touch-icon-72-precomposed.png">
    <link rel="apple-touch-icon-precomposed" href="images/ico/apple-touch-icon-57-precomposed.png">

 </head>
 <body style="background-color:white;">
 <%= yield %>




</body>
</html>